os:
  - linux
language: node_js
node_js:
  - "14"
  - "16"
  - "node"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
install:
  - export CXX=g++-4.9
  - $CXX --version
  - npm install
  - make travis
